version: 2
jobs:
  build:
    working_directory: ~/timing-asgi
    docker:
      - image: themattrix/tox
    steps:
      - run: apt-get update && apt-get install -y openssh-client git
      - checkout
      - run: tox
